### PR TITLE
[mce] Add charging hysteresis control D-Bus constants. JB#58372

### PR DESCRIPTION
**Pull request by martyone**

### CODE REVIEW

**Review by vigejolla — APPROVED** [review]
LGTM

Made me wonder if we should actually publish the documentation somewhere.

**Comment by rainemak** [comment]
> LGTM
> 
> Made me wonder if we should actually publish the documentation somewhere.

Could you please create a task to the bz?

**Comment by vigejolla** [comment]
> Could you please create a task to the bz?

Done, JB#58546

**Comment by martyone** [comment]
Refactored nemo-dbus side to use MCE's settings API instead.

**Pull request closed without merging**
